# Site settings
title: "TheTarotGamer"
email: thetarotgamer@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   The website home of TheTarotGamer. I am the worlds greatest video game
   player. World renowned techno-shaman. I do tarot card readings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thetarotgamer.github.io/"
github_username: thetarotgamer 
twitter_username: realtarotgamer
youtube_username: thetarotgamer 
#twitch_username: thetarotgamer 

# Build settings
markdown: kramdown
port: 4488
permalink: pretty
# Pagination Settings
paginate: 5
paginate_path: "/index/page:num"
# Gems
gems:
    - jekyll-paginate
